### ISSUE TITLE
Please update SDL2 to 2.0.10

### ISSUE THREAD

**Issue by past-due** [snapcrafters/warzone2100#10]
Please update SDL2 to: https://www.libsdl.org/release/SDL2-2.0.10.tar.gz
(which fixes a number of bugs, some of which impact WZ)

**Comment by lucyllewy** [comment]
Hi,

- Which bugs in libsdl 2.0.8 affect Warzone 2100 and in what way?
- How may I reproduce these bugs to verify the their effects and that the new revision fixes them?

**Comment by past-due** [comment]
There are [too many commits](https://hg.libsdl.org/SDL/shortlog/12951) to list all of the bug fixes since SDL 2.0.8 (which was released approx 22 months ago), so here are a selection of examples:

- Polling hid_enumerate() every 3 seconds causes freezes and stutters on some USB audio devices and mice.
https://hg.libsdl.org/SDL/rev/00411ca61edb

- Fixed bug 4094 - No SDL_TEXTEDITING after pressing Alt key on Raspberry Pi Linux
https://hg.libsdl.org/SDL/rev/7f3c9bffada4
Fixing: https://bugzilla.libsdl.org/show_bug.cgi?id=4094

And a subset of the fixes impacting Wayland:

- wayland: Fixed missing window sizing events.
https://hg.libsdl.org/SDL/rev/c4d5e502c1f4
Fixing: https://bugzilla.libsdl.org/show_bug.cgi?id=4242

- wayland: zxdg_shell_v6 needs a configure event before using a surface at all.
https://hg.libsdl.org/SDL/rev/295cf9910d75
Fixing: https://bugzilla.libsdl.org/show_bug.cgi?id=4109

- Fix "unresponsible application" issues in Wayland
https://hg.libsdl.org/SDL/rev/7cec5c0510ae

- wayland: ask KDE protocol extension to use server-side decorations if possible.
https://hg.libsdl.org/SDL/rev/8256aaaafe54


And then, of course, there’s [proper HiDPI support for Wayland](https://hg.libsdl.org/SDL/rev/d92b5fbb5ac0) in SDL 2.0.10 (which will be usable in the soon-to-be-released WZ 3.3.1, and would be immediately usable in the master branch / edge builds... if SDL is updated to 2.0.10 in this snap). That might be the easiest to test with an edge build, if you have a HiDPI display.

**Comment by lucyllewy** [comment]
Thanks for updating :-) I'll merge the PR now, which will start the auto-builder so in an hour there should be a new build in `edge` with the changes (providing the builder doesn't die - the tests here have verified that the snap still builds on amd64 so everything should be good.

**Comment by lucyllewy** [comment]
I've pushed this to stable now
