### ISSUE TITLE
Warzone 2100 3.4.1 release

### ISSUE THREAD

**Issue by past-due** [snapcrafters/warzone2100#17]
3.4.1 is a bug-fix release. It uses the same config folder as 3.4.0, and should not require any build-config changes.

@diddledan: What's the best way to proceed with getting this moved to being part of the upstream repo? (We'd like to automate updating the Snap as part of our automated release process, and we can also better integrate testing of nightly builds of the Snap too.)

**Comment by lucyllewy** [comment]
I'll work-up a PR for you. We can also request the name in the Snap Store be transferred to a project-maintained account so that you have visibility of all the stats and such :-).

**Comment by lucyllewy** [comment]
See warzone2100/warzone2100#1050 :-)

**Comment by lucyllewy** [comment]
3.4.1 successfully built and runs through a quick smoke test, so I've pushed it to stable in the Store.
