### ISSUE TITLE
Moving to CMake builds

### ISSUE THREAD

**Issue by past-due** [snapcrafters/warzone2100#4]
As a heads-up: the [Warzone 2100 Project](https://github.com/Warzone2100) is in the process of transitioning to CMake for builds on all platforms.

The CMake build setup should (I believe) already work for this use-case _[EDIT: On the current master branch]_. We'd definitely like to know about any tweaks / fixes needed, so we can incorporate them before the next release.

**Comment by lucyllewy** [comment]
thanks for the heads' up

**Comment by past-due** [comment]
@diddledan: An update: The autotools build toolchain has now been completely removed, and will not be present in the next WZ release.

EDIT: Also, a full clone (including all tags) is required for the autorevision scripts to properly generate the appropriate versioning information (not sure if this is currently an issue or not).

EDIT[2]:

The following additional build dependencies / packages are now needed: `libcurl4-gnutls-dev gnutls-dev libsodium-dev` (and the respective runtime dependencies).

And you should be able to remove: `libcrypto++-dev libssl-dev`
